### ISSUE TITLE
install error undefined

### ISSUE THREAD

**Issue by beckietech** [Unbewohnte/id3ed#1]
hi, 
I want to install this library by using README, however, I got this error
go/src/github.com/Unbewohnte/id3ed/v2/write.go:166:15: undefined: os.CreateTemp

May I know how this hapeen?

**Comment by Unbewohnte** [comment]
Hello !
I`ve tried to recreate this issue, but it seems that ID3v2 frame replacing works as expected.

![1](https://user-images.githubusercontent.com/65883674/149610366-c4e5a2db-cae0-4935-b03a-120161f6dce1.png)

![2](https://user-images.githubusercontent.com/65883674/149610372-fd8881cc-cd38-4992-8ea4-15ff4cba01c6.png)

There`s not enough information for me to determine what exactly goes wrong in your situation.

Maybe you have a ve~ry old Go compiler ?  In this case this library will not work for you (because many os functions were in ioutil package instead before). Good idea would be to update.

Feel free to discuss !
